### ISSUE TITLE
system.query_log read_rows and read_bytes is empty after select

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3607]
## Summary

ClickHouse handler reset the context progress cause the read_rows/bytes to empty(MySQL handler works):
```
 query_kind: SelectPlan
         query_text:  SELECT OriginCityName, count(*) AS c FROM ontime GROUP BY OriginCityName ORDER BY c DESC L
IMIT 10;
         event_date: 2021-12-23
         event_time: 2021-12-23 02:11:10
   current_database: default
          databases: 
             tables: 
            columns: 
        projections: 
       written_rows: 0
      written_bytes: 0
          read_rows: 0
         read_bytes: 0
        result_rows: 10
       result_bytes: 301
          cpu_usage: 4
       memory_usage: 3539
        client_info: 
```
