### ISSUE TITLE
bug:  There maybe have some thing worry with stream load 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4583]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.6.102-nightly-9e4c5ae-simd

### What's Wrong?
```
wget  --no-check-certificate --continue "https://repo.databend.rs/m_ontime/ontime_005.csv"

curl -H "insert_sql:insert into ontime format CSV" -H "field_delimiter:'\t'" -H "skip_header:0" -H "record_delimiter:'\n'" -F "upload=@ontime_005.csv" -XPUT http://localhost:8000/v1/s
treaming_load
```
{"id":"0304a9f1-ba2a-4505-bf2f-8ef6b1d6cf23","state":"SUCCESS","stats":{"rows":1,"bytes":1083},"error":null}

But  only two columns have to value ,the other columns just  '0'

Use copy into :
```
copy into ontime   from 's3://repo.databend.rs/m_ontime/ontime_005.csv'   file_format = (type = 'CSV' field_delimiter = '\t'  record_delimiter = '\n' skip_header = 0);
```
Looks every thing ok.

### What You Expected?

Make stream load result is ok. 

### How to Reproduce?
```
wget  --no-check-certificate --continue "https://repo.databend.rs/m_ontime/ontime_005.csv"

curl -H "insert_sql:insert into ontime format CSV" -H "field_delimiter:'\t'" -H "skip_header:0" -H "record_delimiter:'\n'" -F "upload=@ontime_005.csv" -XPUT http://localhost:8000/v1/s
treaming_load
```

**Comment by BohuTANG** [comment]
Please try:
```
curl -H "insert_sql:insert into ontime format CSV" -H "field_delimiter:'\t'" -H "record_delimiter = '\n'" -H "skip_header:0" -H "record_delimiter:'\n'" -F "upload=@ontime_005.csv" -XPUT http://localhost:8000/v1/s
treaming_load
```

**Comment by sundy-li** [comment]
> But only to columns have to value ,the other columns just '0'

What does it mean?

**Comment by wubx** [comment]
> > But only to columns have to value ,the other columns just '0'
> 
> What does it mean?  

sorry . to replace two 
```
curl -H "insert_sql:insert into ontime format CSV" -H "field_delimiter:'\t'" -H "record_delimiter = '\n'" -H "skip_header:0" -H "record_delimiter:'\n'" -F "upload=@ontime_005.csv" -XPUT http://localhost:8000/v1/streaming_load

 head -n 1 ontime_005.csv
1989    3       9       9       6       1989-09-09      DL      19790   DL              72      12892   1289201 32575   LAX     Los Angeles, CA CA      06      California      91      11298   1129801 30194   DFW    Dallas/Fort Worth, TX    TX      48      Texas   74      1755    1755    0       0       0       0       1700-1759       0       0       0       0       2245    2235    10      0       0       -1      2200-2259      00       170     160     0       1       1235    5       0       0       0       0       0                                                                               0       0                                      00                                                       0       0                                                       0       0                                                       0       0
```
{"id":"ab9fe30d-f0df-43cb-b5a5-377f3da4cc04","state":"SUCCESS","stats":{"rows":1,"bytes":1083},"error":null}

like this:
```
mysql> select * from ontime limit 1 \G;
*************************** 1. row ***************************
                           Year: 1989
                        Quarter: 0
                          Month: 0
                     DayofMonth: 0
                      DayOfWeek: 0
                     FlightDate: 1970-01-01
              Reporting_Airline:
       DOT_ID_Reporting_Airline: 0
    IATA_CODE_Reporting_Airline:
                    Tail_Number:
Flight_Number_Reporting_Airline:
                OriginAirportID: 0
             OriginAirportSeqID: 0
             OriginCityMarketID: 0
                         Origin:
                 OriginCityName:
                    OriginState:
                OriginStateFips:
                OriginStateName:
                      OriginWac: 0
                  DestAirportID: 0
               DestAirportSeqID: 0
               DestCityMarketID: 0
                           Dest:
                   DestCityName:
                      DestState:
                  DestStateFips:
                  DestStateName:
                        DestWac: 0
                     CRSDepTime: 0
                        DepTime: 0
                       DepDelay: 0
                DepDelayMinutes: 0
                       DepDel15: 0
           DepartureDelayGroups:
                     DepTimeBlk:
                        TaxiOut: 0
                      WheelsOff: 0
                       WheelsOn: 0
                         TaxiIn: 0
                     CRSArrTime: 0
                        ArrTime: 0
                       ArrDelay: 0
                ArrDelayMinutes: 0
                       ArrDel15: 0
             ArrivalDelayGroups: 0
                     ArrTimeBlk:
                      Cancelled: 0
               CancellationCode:
                       Diverted: 0
                 CRSElapsedTime: 0
              ActualElapsedTime: 0
                        AirTime: 0
                        Flights: 0
                       Distance: 0
                  DistanceGroup: 0
                   CarrierDelay: 0
                   WeatherDelay: 0
                       NASDelay: 0
                  SecurityDelay: 0
              LateAircraftDelay: 0
                   FirstDepTime:
                  TotalAddGTime:
                LongestAddGTime:
             DivAirportLandings:
                 DivReachedDest:
           DivActualElapsedTime:
                    DivArrDelay:
                    DivDistance:
                    Div1Airport:
                  Div1AirportID: 0
               Div1AirportSeqID: 0
                   Div1WheelsOn:
                 Div1TotalGTime:
               Div1LongestGTime:
                  Div1WheelsOff:
                    Div1TailNum:
                    Div2Airport:
                  Div2AirportID: 0
               Div2AirportSeqID: 0
                   Div2WheelsOn:
                 Div2TotalGTime:
               Div2LongestGTime:
                  Div2WheelsOff:
                    Div2TailNum:
                    Div3Airport:
                  Div3AirportID: 0
               Div3AirportSeqID: 0
                   Div3WheelsOn:
                 Div3TotalGTime:
               Div3LongestGTime:
                  Div3WheelsOff:
                    Div3TailNum:
                    Div4Airport:
                  Div4AirportID: 0
               Div4AirportSeqID: 0
                   Div4WheelsOn:
                 Div4TotalGTime:
               Div4LongestGTime:
                  Div4WheelsOff:
                    Div4TailNum:
                    Div5Airport:
                  Div5AirportID: 0
               Div5AirportSeqID: 0
                   Div5WheelsOn:
                 Div5TotalGTime:
               Div5LongestGTime:
                  Div5WheelsOff:
                    Div5TailNum:
1 row in set (0.07 sec)
Read 1 rows, 1.08 KB in 0.068 sec., 14.6 rows/sec., 15.82 KB/sec.
```
