### ISSUE TITLE
Support auth for ClickHouse REST with vector

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4637]
**Summary**

https://vector.dev/docs/reference/configuration/sinks/clickhouse/#auth

**Comment by youngsofun** [comment]
basic auth has been supported (bear auth should have too).

I test on my local Nginx and vector:

```
create user 'u1' identified by 'p1';
GRANT insert ON nginx_logs TO 'u1'@'%';
```

add this to vector.toml

```toml
[sinks.databend_sink.auth]
strategy = "basic"
user = "u1"
password = "p1"
```
