### ISSUE TITLE
system.query_log return empty result with DateTime64 type

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4645]
**Summary**

```
mysql> show create table system.query_log\G;
*************************** 1. row ***************************
       Table: query_log
Create Table: CREATE TABLE `query_log` (
  `log_type` Int8,
  `handler_type` String,
  `tenant_id` String,
  `cluster_id` String,
  `sql_user` String,
  `sql_user_quota` String,
  `sql_user_privileges` String,
  `query_id` String,
  `query_kind` String,
  `query_text` String,
  `event_date` Date32,
  `event_time` DateTime64(3),
  `current_database` String,
  `databases` String,
  `tables` String,
  `columns` String,
  `projections` String,
  `written_rows` UInt64,
  `written_bytes` UInt64,
  `written_io_bytes` UInt64,
  `written_io_bytes_cost_ms` UInt64,
  `scan_rows` UInt64,
  `scan_bytes` UInt64,
  `scan_io_bytes` UInt64,
  `scan_io_bytes_cost_ms` UInt64,
  `scan_partitions` UInt64,
  `total_partitions` UInt64,
  `result_rows` UInt64,
  `result_bytes` UInt64,
  `cpu_usage` UInt32,
  `memory_usage` UInt64,
  `client_info` String,
  `client_address` String,
  `exception_code` Int32,
  `exception_text` String,
  `stack_trace` String,
  `server_version` String,
  `session_settings` String,
  `extra` String,
) ENGINE=SystemQueryLog

```

table data:
```
*************************** 13. row ***************************
                log_type: 1
            handler_type: ClickhouseHTTPHandler
               tenant_id: admin
              cluster_id: 
                sql_user: root
          sql_user_quota: UserQuota<cpu:0,mem:0,store:0>
     sql_user_privileges: GRANT ALL ON *.* TO 'root'@'127.0.0.1', ROLES: []
                query_id: 599b633b-7231-4e95-af0e-a28659e03be7
              query_kind: InsertPlan
              query_text: INSERT INTO "nginx"."access_logs" FORMAT JSONEachRow
              event_date: 2022-03-31
              event_time: 2022-03-31 11:31:03.380
        current_database: default
               databases: 
                  tables: 
                 columns: 
             projections: 
            written_rows: 0
           written_bytes: 0
        written_io_bytes: 0
written_io_bytes_cost_ms: 0
               scan_rows: 0
              scan_bytes: 0
           scan_io_bytes: 0
   scan_io_bytes_cost_ms: 0
         scan_partitions: 0
        total_partitions: 0
             result_rows: 0
            result_bytes: 0
               cpu_usage: 16
            memory_usage: 1579
             client_info: 
          client_address: 
          exception_code: 0
          exception_text: 
             stack_trace: 
          server_version: 
        session_settings: enable_new_processor_framework=1, flight_client_timeout=60, max_block_size=10000, max_threads=16, storage_occ_backoff_init_delay_ms=5, storage_occ_backoff_max_delay_ms=20000, storage_occ_backoff_max_elapsed_ms=120000, storage_read_buffer_size=1048576, scope: SESSION
                   extra: 
*************************** 14. row ***************************
                log_type: 1
            handler_type: ClickhouseHTTPHandler
               tenant_id: admin
              cluster_id: 
                sql_user: root
          sql_user_quota: UserQuota<cpu:0,mem:0,store:0>
     sql_user_privileges: GRANT ALL ON *.* TO 'root'@'127.0.0.1', ROLES: []
                query_id: a17e474d-01de-46e7-ac4a-042db89591c8
              query_kind: InsertPlan
              query_text: INSERT INTO "nginx"."access_logs" FORMAT JSONEachRow
              event_date: 2022-03-31
              event_time: 2022-03-31 11:34:56.470
        current_database: default
               databases: 
                  tables: 
                 columns: 
             projections: 
            written_rows: 0
           written_bytes: 0
        written_io_bytes: 0
written_io_bytes_cost_ms: 0
               scan_rows: 0
              scan_bytes: 0
           scan_io_bytes: 0
   scan_io_bytes_cost_ms: 0
         scan_partitions: 0
        total_partitions: 0
             result_rows: 0
            result_bytes: 0
               cpu_usage: 16
            memory_usage: 1579
             client_info: 
          client_address: 
          exception_code: 0
          exception_text: 
             stack_trace: 
          server_version: 
        session_settings: enable_new_processor_framework=1, flight_client_timeout=60, max_block_size=10000, max_threads=16, storage_occ_backoff_init_delay_ms=5, storage_occ_backoff_max_delay_ms=20000, storage_occ_backoff_max_elapsed_ms=120000, storage_read_buffer_size=1048576, scope: SESSION
                   extra: 

```

Query:
```
mysql> select * from system.query_log where query_kind='InsertPlan' and event_time >'2022-03-31 11:31:03.380'\G;
Query OK, 0 rows affected (0.10 sec)
Read 134 rows, 129.08 KB in 0.091 sec., 1.48 thousand rows/sec., 1.42 MB/sec.

ERROR: 
No query specified

```
