### ISSUE TITLE
Feature: Switch to disable stdout log or file log

### ISSUE THREAD

**Issue by DCjanus** [datafuselabs/databend#5006]
## Summary

Maybe there should be a switch to disable stdout log or file log, in the real world deploy, log storage is a serious problem.

## Detail
For example, some companies running applitions in docker and collect logs from stdout, via docker log drive, to log service. But for now, databend can't disable file output for logging, because of [those lines](https://github.com/datafuselabs/databend/blob/213c196fc0d2d4335c4dddc3fcc26b66af872f51/common/tracing/src/logging.rs#L83-L86).

Because in the real world, stateless service, like databend-query, may running in a shared k8s cluster to reduce machine cost, and each k8s node may host more than 100 pods. If all of them write logs to disk, the cost of IO and space would be really expensive. 

Actual, some companies to avoid this issue, they've developed some file systems to hold log files in memory and offload data to remote storage on the fly.

Maybe the new logging configurations should be look like this:
```toml
[log.stdout]
enable = true
json = true
color = false
level = "info"

[log.file]
enable = true
dir = "./logs"
json = true
level = "error"
```
