### ISSUE TITLE
Add docs for new config log.file.format & log.stderr.format

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#8487]
**Summary**

PR #8466 introduces two new config to control logging:

```toml
[log.file]
format = "json"

[log.stderr]
format = "text"
```

Now, our users can control the different logging format for `file` and `stderr`.

- If format is `text`, we will output plain text logging (stderr's default)
- If format is `json`, we will output json logging (file's default)

Cc @soyeric128, can you help to adding them in our docs?
