### ISSUE TITLE
bug:  catalog info is lost if databend-query restart

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#9069]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

48077712546fe03f533887735793a3caee0c0858

### What's Wrong?

catalog info is lost if databend-query restart

### How to Reproduce?

1. CREATE CATALOG hive   TYPE=HIVE   CONNECTION = (ADDRESS='lt.hive-ro-metastore-meta.internal:9083' THRIFT_PROTOCOL=BINARY);
2. restart databend-query
3. select * from default.system.catalogs;   no hive catalog

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
cc @ClSlaid, Please take a look.

**Comment by ClSlaid** [comment]
Currently, multiple catalogs feature is still in process, the missing piece is that external catalogs are not managed by `metasrv`, so every time the databend-query shuts down, all external catalogs created by SQL will be lost.

For now, if you want to continue using external catalog, please write catalogs you want in configuration file. The example of new version of configuration:

```toml
# hive catalog
[catalogs.<catalog_name>]
type = "hive"
address = "<hive_address>"
protocol = "binary"  # currently only supported this, it's ok to ommit.
```

or reuse your old version configuration

```toml
# hive catalog
[catalog]
meta_store_address = "127.0.0.1:9083"
protocol = "binary"
```
